### ISSUE TITLE
Marketplace --> Application Information (Empty Fields)

### ISSUE THREAD

**Issue by GaaTY** [gladiusio/gladius-node#64]
I'm assuming this section is 'supposed' to read data from a previous version installation and populate it in there. As of now, the fields are just empty. Application to a pool can only succeed when the information has AGAIN been entered.

![image](https://user-images.githubusercontent.com/17968700/44456374-9e3feb00-a600-11e8-8100-0fe2d9ac57aa.png)

**Comment by overtfuture** [comment]
We didn't implement any type of migration between beta launches. We are using the same wallet, but the actual profile has moved from being stored encrypted on the blockchain to a pool's application server.

This information tab just keeps a local copy of contact info to "autofill" applications. Each pool application will actually be its own separate profile.

In the future, we do not have plans to make a "universal profile" that can be retrieved because it goes against the decentralized nature of our project. The only identifying factor shared between pools that you apply to is your wallet address.
